name: Automata
main: MattTwoPointOh.Automata.AutomataPlugin
version: __VERSION_MACRO__
commands:
  clearcarts:
    description: Clears all minecarts.
    usage: /command
  clearrails:
    description: Clears all minecart rails.
    usage: /command